### ISSUE TITLE
Sorry don't know how else to contact you.

### ISSUE THREAD

**Issue by Swizzler121** [ohait/jmy6xx#1]
Hey. Any idea where to buy these modules in small quantities? I'm needing a ISO15693 module for a project and this is the only arduino compatible non-NFC modules I can find, but I can't find them ANYWHERE online. They aren't on ebay, they've been discontinued from aliexpress... can you only get them in bulk from the company?

**Comment by ohait** [comment]
You can get them from the company, they sold me only 1 exemplar once when i was testing

Let me know if you need more help
